In [3]:
# Imports
import numpy as np
import torch

from phimal_utilities.data import Dataset
from phimal_utilities.data.burgers import BurgersDelta




In [52]:
v = 0.1
A = 1.0

# Making grid
x = np.linspace(-3, 4, 100)
t = np.linspace(0.5, 5.0, 50)
x_grid, t_grid = np.meshgrid(x, t, indexing='ij')

# Making data
dataset = Dataset(BurgersDelta, v=v, A=A)

X_train, y_train, rand_idx = dataset.create_dataset(x_grid.reshape(-1, 1), t_grid.reshape(-1, 1), n_samples=1000, noise=0.1, random=True, return_idx=True)
    
theta = dataset.library(x_grid.reshape(-1, 1), t_grid.reshape(-1, 1), poly_order=2, deriv_order=3)[rand_idx, :]
dt = dataset.time_deriv(x_grid.reshape(-1, 1), t_grid.reshape(-1, 1))[rand_idx, :] 

In [53]:
theta = torch.tensor(theta)
dt = torch.tensor(dt)

norm = torch.norm(theta, dim=0, keepdim=True)

In [54]:
Sigma = torch.svd(theta / norm)[1]
Sigma.max() / Sigma.min()

tensor(76.4501, dtype=torch.float64)

In [60]:
Q, R = torch.qr(theta)
torch.inverse(R) @ Q.T @ dt

tensor([[ 8.6736e-18],
        [ 1.8041e-16],
        [ 1.0000e-01],
        [ 4.3368e-18],
        [-3.8858e-16],
        [-1.0000e+00],
        [ 3.3307e-16],
        [ 1.7347e-17],
        [ 1.3323e-15],
        [ 2.2204e-15],
        [ 0.0000e+00],
        [ 3.1225e-17]], dtype=torch.float64)

In [63]:
Q, R = torch.qr(theta / norm)
torch.inverse(R) @ Q.T @ dt / norm.T

tensor([[ 2.0187e-17],
        [ 5.6790e-16],
        [ 1.0000e-01],
        [-9.7281e-18],
        [-5.2974e-16],
        [-1.0000e+00],
        [-3.3268e-16],
        [-1.7562e-17],
        [-8.1816e-16],
        [ 2.1413e-15],
        [ 1.4778e-16],
        [ 5.7686e-17]], dtype=torch.float64)

In [62]:
norm

tensor([[ 31.6228,   9.7747,  34.8590, 243.9429,   7.5448,   5.2526,  26.6973,
         151.7229,   4.3423,   3.9405,  24.0408, 120.2876]],
       dtype=torch.float64)

In [58]:
Sigma = torch.svd(R)[1]
Sigma.max() / Sigma.min()

tensor(76.4501, dtype=torch.float64)

In [36]:
np.up

tensor([[-1.0000,  0.0152,  0.0415, -0.0211, -0.5831,  0.0278,  0.1365, -0.0185,
         -0.4146,  0.0288,  0.1273,  0.0026],
        [ 0.0000, -0.9999, -0.1128,  0.6207,  0.0538, -0.8835, -0.2410,  0.6159,
          0.0783, -0.7159, -0.2562,  0.5129],
        [ 0.0000,  0.0000,  0.9928,  0.0960, -0.4110,  0.2473,  0.8808,  0.1105,
         -0.6177,  0.3623,  0.8223,  0.0489],
        [ 0.0000,  0.0000,  0.0000,  0.7778,  0.0540, -0.2415,  0.1285,  0.6822,
         -0.0093, -0.2790,  0.0979,  0.5933],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.6966,  0.1260, -0.0470, -0.0629,
          0.5949,  0.1828, -0.0400, -0.1439],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000, -0.2886, -0.1214,  0.2307,
         -0.1262, -0.4637, -0.1150,  0.3531],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000, -0.3377,  0.0551,
          0.2026, -0.0536, -0.4607,  0.0314],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000, -0.2871,
          0.0403,  0.1084, -0.